#!/bin/bash

# This performs the CP-specific PoV harness. It may be replaced with a script
# or binary for a different interpreter. The name MUST NOT change.

set -e
set -o pipefail

warn() {
    echo "$*" >&2
}

die() {
    warn "$*"
    exit 1
}

BLOB_FILE=${1:-}
HARNESS_FILE=${OUT}/${2:-}

export ASAN_OPTIONS=detect_leaks=0

[[ -f "${BLOB_FILE}" ]] || die "Invalid input, missing blob file: $BLOB_FILE"
[[ -x "${HARNESS_FILE}" ]] || die "Invalid input, missing harness file: $HARNESS_FILE"

bash -c "$HARNESS_FILE $BLOB_FILE" || true
